server:
  port: 8761

eureka:
   instance:
       hostname: firstRegister
       prefer-ip-address: true
       instance-id: ${spring.cloud.client.ip-address}:${server.port}
       lease-renewal-interval-in-seconds: 3
       lease-expiration-duration-in-seconds: 7
   client:
       register-with-eureka: false
       fetch-registry: false
       serviceUrl:
            defaultZone: http://yhy:123@secondRegister:8762/eureka/
   server:
        waitTimeInMsWhenSyncEmpty: 60
        enableSelfPreservation: false
        eviction-interval-timer-in-ms: 3000
  
spring:
   security:
      user:
         name: yhy
         password: 123
   application:
         name: register
