server:
  port: 8762

eureka:
   instance:
       hostname: secondRegister
       prefer-ip-address: false
       lease-renewal-interval-in-seconds: 3
       lease-expiration-duration-in-seconds: 7
   client:
       register-with-eureka: false
       fetch-registry: false
       serviceUrl:
            defaultZone: http://yhy:ry19970418!@firstRegister:8761/eureka/
   server:
        waitTimeInMsWhenSyncEmpty: 60
        enableSelfPreservation: false
        eviction-interval-timer-in-ms: 3000
  
spring:
   security:
      user:
         name: yhy
         password: ry19970418!
   application:
         name: secondRegister
