server:
   port: 8888
   
spring:
  application:
    name: configServer
  http:
      encoding:
          force: true
          charset: UTF-8
          enabled: true
          uri-encoding: UTF-8  
  security:
      user:
         name: yhy
         password: ry19970418!
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hongyuYaoChinese/configPackage.git
          username: 18698655352@163.com
          password: ry19970418!
  rabbitmq:
      host: rabbitmqHost
      port: 5672
      username: yhy
      password: ry19970418!
      
eureka:
   instance:
        leaseRenewalIntervalInSeconds: 10
        leaseExpirationDurationInSeconds: 30
        appname: configServer
   client:
       register-with-eureka: true
       fetch-registry: true
       serviceUrl:
         defaultZone: http://yhy:ry19970418!@firstRegister:8761/eureka/,http://yhy:ry19970418!@secondRegister:8762/eureka/